---

- name: Update apt cache
  apt:
   update_cache: yes

- name: Install rsyslog-gnutls
  apt:
   name: rsyslog-gnutls
   state: present
  when: papertrailapp_tls
   notify:
    - syslog restart

- name: Installing remote_syslog
  apt:
   name: "{{ remote_syslog_url_deb }}"
   state: present
